export const VOTE_REQUEST = 'VOTE_REQUEST';
export const VOTE_REQUEST_CONFIRMED = 'VOTE_REQUEST_CONFIRMED';
export const VOTE_REQUEST_CANCELED = 'VOTE_REQUEST_CANCELED';
export const VOTE_REQUEST_SUCCESS = 'VOTE_REQUEST_SUCCESS';
export const VOTE_REQUEST_FAIL = 'VOTE_REQUEST_FAIL';